spring:
  application:
    name: spring-boot-tracker-manager-service

  main:
    banner-mode: "off"  # Disable startup banner

  banner:
    location: classpath:banner.txt  # Custom banner file

  security:
    user:
      name: admin     # Admin username (override via env variable)
      password: admin  # Admin password (override via env variable)
      roles: ACTUATOR_ADMIN

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tracker_manager_db
    username: postgres   # Securely fetch from env variable
    password: root       # Securely fetch from env variable
    properties:
      charSet: UTF-8
    hikari:
      minimum-idle: 2
      maximum-pool-size: 25
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
      schema: dev

  # JPA & Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: dev
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
          lob:
            non_contextual_creation: true  # Prevents unnecessary warnings for BLOB fields

  mail:
    host: smtp.gmail.com
    port: 587
    username: <YOUR_GMAIL_EMAIL_ID>
    password: <YOUR_GOOGLE_APP_PASSWORD>
    email-subject: 🔐 Reset Your Password - Tracker Manager
    email-body: "<div style='font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 30px;'><div style='max-width: 550px; margin: auto; background: #ffffff; padding: 25px; border-radius: 12px; box-shadow: 0px 6px 12px rgba(0,0,0,0.15);'><div style='text-align: center; padding-bottom: 15px; border-bottom: 2px solid #007bff;'><h2 style='color: #007bff; margin: 0;'>🔐 Password Reset Request</h2></div><p style='font-size: 16px; color: #333;'>Dear <strong>{EMAIL}</strong>,</p><p style='font-size: 15px; color: #555;'>We received a request to reset your password. Use the OTP below to proceed:</p><div style='font-size: 26px; font-weight: bold; text-align: center; background: linear-gradient(135deg, #007bff, #00d4ff); color: white; padding: 12px; border-radius: 6px; letter-spacing: 2px;'>{OTP_CODE}</div><p style='margin-top: 20px; font-size: 14px; color: #555;'>This OTP is valid for <strong>10 minutes</strong>. Please do not share it with anyone.</p><div style='text-align: center; margin-top: 20px;'><a href='{RESET_LINK}' style='background: #007bff; color: white; text-decoration: none; padding: 12px 20px; border-radius: 6px; font-size: 16px; display: inline-block;'>Reset Password</a></div><hr style='margin-top: 25px; border: none; height: 1px; background: #ddd;'><p style='text-align: center; font-size: 12px; color: #777;'>Need help? <a href='mailto:siddhantpatni04@gmail.com' style='color: #007bff; text-decoration: none;'>Contact Support</a><br>&copy; 2025 Tracker Manager. All rights reserved.</p></div></div>"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

stock-market:
  nifty-50:
    url: https://www.nseindia.com/api/equity-stockIndices

encryption:
  aes:
    algorithm: AES
    secret-key: Xf9aLp3qzT7vN2sYgW5KbVc6Rm8QJ0dP

app:
  backup:
    directory: C:\Backup\Database\tracker_manager_db  # Change this to your desired backup location
    prefix: db_backup
    default-db: tracker_manager_db

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8069  # Server port, configurable via environment variable

webclient:
  config:
    memory-buffer-size: 524288
    timeout: 30
    retry:
      max-retry: 1
      delay: 5

# Logging Configuration
logging:
  level:
    root: INFO  # More detailed logs in development
    com.sid: INFO