spring:
  application:
    name: spring-boot-tracker-manager-service

  # Set Active Profile via Environment Variable (default: dev)
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  main:
    banner-mode: "off"  # Disable startup banner

  banner:
    location: classpath:banner.txt  # Custom banner file

  security:
    user:
      name: ${ADMIN_USERNAME}      # Admin username (override via env variable)
      password: ${ADMIN_PASSWORD}  # Admin password (override via env variable)
      roles: ACTUATOR_ADMIN

  # Liquibase Configuration (For Database Versioning)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  # Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}   # Securely fetch from env variable
    password: ${DB_PASSWORD}       # Securely fetch from env variable
    properties:
      charSet: UTF-8
    hikari:
      minimum-idle: 2
      maximum-pool-size: 25
      idle-timeout: 10000
      pool-name: HikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
      schema: dev

  # JPA & Hibernate Configuration
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: dev
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true  # Prevents unnecessary warnings for BLOB fields

server:
  port: ${SERVER_PORT:8069}  # Server port, configurable via environment variable

# Logging Configuration
logging:
  level:
    root: INFO
    com.sid: INFO  # Debug mode enabled for specific package